default: &default
  db_username: <%= ENV['DB_USERNAME'] %>
  db_password: <%= ENV['DB_PASSWORD'] %>
  db_database: <%= ENV['DB_DATABASE'] %>
  db_encoding: <%= ENV['DB_ENCODING'] %>
  db_pool: <%= ENV['DB_POOL'] %>
  db_host: <%= ENV['DB_HOST'] %>
  db_port: <%= ENV['DB_PORT'] %>

  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

  api:
    token: <%= ENV['API_TOKEN'] %>

development:
  <<: *default

qa:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default